[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/136867?v=4"'
alt = 'Avatar of Anne Archibald'
{{< /image >}}
Anne Archibald'''
link = 'https://github.com/aarchiba'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/16557411?u=3a754c87deb564d547557e084e7a1b348371b763&v=4"'
alt = 'Avatar of Antonio Horta Ribeiro'
{{< /image >}}
Antonio Horta Ribeiro'''
link = 'https://github.com/antonior92'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/101416?v=4"'
alt = 'Avatar of argriffing'
{{< /image >}}
argriffing'''
link = 'https://github.com/argriffing'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/8453868?u=c21c34ef9293ef4b27b6c36f46701a59b7841424&v=4"'
alt = 'Avatar of Cathy Douglass'
{{< /image >}}
Cathy Douglass'''
link = 'https://github.com/cdouglass'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/25111?v=4"'
alt = 'Avatar of David Cournapeau'
{{< /image >}}
David Cournapeau'''
link = 'https://github.com/cournape'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/1046124?u=46dcb9a8dd50ffbb339649a6d708624c2a63e7bc&v=4"'
alt = 'Avatar of Denis Laxalde'
{{< /image >}}
Denis Laxalde'''
link = 'https://github.com/dlax'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/6894112?u=e46d0de3c71bd891c10bfbf3dbb952074ea6405b&v=4"'
alt = 'Avatar of Eric Quintero'
{{< /image >}}
Eric Quintero'''
link = 'https://github.com/e-q'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/2314641?v=4"'
alt = 'Avatar of Eric Moore'
{{< /image >}}
Eric Moore'''
link = 'https://github.com/ewmoore'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/277639?u=76b14735220a371f55d0cacf208d6d3aee4deb00&v=4"'
alt = 'Avatar of Fabian Pedregosa'
{{< /image >}}
Fabian Pedregosa'''
link = 'https://github.com/fabianp'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/1847484?v=4"'
alt = 'Avatar of Ian Henriksen'
{{< /image >}}
Ian Henriksen'''
link = 'https://github.com/insertinterestingnamehere'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/3343990?v=4"'
alt = 'Avatar of Jaime'
{{< /image >}}
Jaime'''
link = 'https://github.com/jaimefrio'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/781659?u=07b92bc956bbc8db74533b7cd9c80ca5175fdb2c&v=4"'
alt = 'Avatar of Jake Vanderplas'
{{< /image >}}
Jake Vanderplas'''
link = 'https://github.com/jakevdp'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/123428?v=4"'
alt = 'Avatar of Jarrod Millman'
{{< /image >}}
Jarrod Millman'''
link = 'https://github.com/jarrodmillman'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/335383?v=4"'
alt = 'Avatar of Lars'
{{< /image >}}
Lars'''
link = 'https://github.com/larsmans'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/402156?u=288a1f206a151f9e2b69f3c0ce11848d3381943e&v=4"'
alt = 'Avatar of Pearu Peterson'
{{< /image >}}
Pearu Peterson'''
link = 'https://github.com/pearu'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/320553?u=d25e1b8b91eea8f1fc8ff22a003f315527746bf8&v=4"'
alt = 'Avatar of Anthony Scopatz'
{{< /image >}}
Anthony Scopatz'''
link = 'https://github.com/scopatz'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/10172976?u=38efc9551796031d81250c19e44516972cfec742&v=4"'
alt = 'Avatar of Seth Troisi'
{{< /image >}}
Seth Troisi'''
link = 'https://github.com/sethtroisi'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/254880?v=4"'
alt = 'Avatar of Travis E. Oliphant'
{{< /image >}}
Travis E. Oliphant'''
link = 'https://github.com/teoliphant'
