[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/57562633?u=18373b73b2a525bb643839433e3d1ea605a7c88b&v=4"
    alt="Avatar of Martin Schuck"
>}}
Martin Schuck'''
link = 'https://github.com/amacati'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/23621655?u=525aca83e7dda8d8474e35c0edc5a233af2f8bde&v=4"
    alt="Avatar of Anirudh Dagar"
>}}
Anirudh Dagar'''
link = 'https://github.com/AnirudhDagar'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/6213168?u=b69e5910ac6277e04ddd1723c91811d96b3eb49a&v=4"
    alt="Avatar of Guido Imperiale"
>}}
Guido Imperiale'''
link = 'https://github.com/crusaderky'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/36567889?v=4"
    alt="Avatar of czgdp1807"
>}}
czgdp1807'''
link = 'https://github.com/czgdp1807'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/58611?v=4"
    alt="Avatar of endolith"
>}}
endolith'''
link = 'https://github.com/endolith'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/10579828?v=4"
    alt="Avatar of fancidev"
>}}
fancidev'''
link = 'https://github.com/fancidev'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/10298716?u=f3e56f5ed08607db75e9e6ee22caa82bb7452110&v=4"
    alt="Avatar of Florian Bourgey"
>}}
Florian Bourgey'''
link = 'https://github.com/fbourgey'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/11718923?u=c20851d8f7dcd9373557fb7b1a64774214d58fa1&v=4"
    alt="Avatar of Filipe Laíns"
>}}
Filipe Laíns'''
link = 'https://github.com/FFY00'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/6208662?u=f5b6702cd80c1cd85d9a9cdc84fee65bedae24ca&v=4"
    alt="Avatar of Joren Hammudoglu"
>}}
Joren Hammudoglu'''
link = 'https://github.com/jorenham'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/14363975?u=1b2685931a63e81d379f7ec657d97456dc6eca0d&v=4"
    alt="Avatar of Scott Shambaugh"
>}}
Scott Shambaugh'''
link = 'https://github.com/scottshambaugh'
