[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/40656107?u=ec1b5e41026e08a37464489f421f0eac3474d1b1&v=4"
    alt="Avatar of Daniel Schmitz"
>}}
Daniel Schmitz'''
link = 'https://github.com/dschmitz89'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/2133832?v=4"
    alt="Avatar of Evgeni Burovski"
>}}
Evgeni Burovski'''
link = 'https://github.com/ev-br'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/10298716?u=f3e56f5ed08607db75e9e6ee22caa82bb7452110&v=4"
    alt="Avatar of Florian Bourgey"
>}}
Florian Bourgey'''
link = 'https://github.com/fbourgey'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/482179?u=cb5097768995bdbbce1a7388e853ae381e757e84&v=4"
    alt="Avatar of Irwin Zaid"
>}}
Irwin Zaid'''
link = 'https://github.com/izaid'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/51488791?u=57da3ab3e223374ed21bad2b965fced84e6a397c&v=4"
    alt="Avatar of Lucas Colley"
>}}
Lucas Colley'''
link = 'https://github.com/lucascolley'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/6570539?u=cfb3e218754e85c4fac18064d7cfdce0b67ddaa6&v=4"
    alt="Avatar of Matt Haberland"
>}}
Matt Haberland'''
link = 'https://github.com/mdhaber'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''
{{< image
    src="https://avatars.githubusercontent.com/u/1953382?u=f1ab59dca0a793968a5a84d8368b60d56b1ab467&v=4"
    alt="Avatar of Albert Steppi"
>}}
Albert Steppi'''
link = 'https://github.com/steppi'
