languageName: Japanese
params:
  description: Why SciPy? Fundamental algorithms. Broadly applicable. Foundational. Interoperable. Performant. Open source.
  navbarlogo:
    image: logo.svg
    altText: A blue circle with a snake in the shape of the letter 'S'.
    text: SciPy
    link: /ja/
  hero:
    # Main hero title
    title: SciPy
    # Hero subtitle (optional)
    subtitle: Fundamental algorithms for scientific computing in Python
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/ja/install"
    # Hero image (from static/images/___)
    image: logo.svg

  section5: false

  navbar:
    - title: Install
      url: /ja/install
    - title: Documentation
      url: https://docs.scipy.org/doc/scipy/
    - title: Community
      url: /ja/community
    - title: About Us
      url: /ja/about
    - title: Contribute
      url: /ja/contribute
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/scipy/scipy
        icon: github
      - link: https://discuss.scientific-python.org/c/contributor/scipy/
        icon: scientific-python
    quicklinks:
      column1:
        title: ""
        links:
          - text: Install
            link: /ja/install
          - text: Documentation
            link: https://docs.scipy.org/doc/scipy/
          - text: Citing SciPy
            link: /ja/citing-scipy
          - text: Roadmap
            link: https://scipy.github.io/devdocs/dev/roadmap.html
      column2:
        links:
          - text: About Us
            link: /ja/about
          - text: Community
            link: /ja/community
          - text: SciPy Conference
            link: https://conference.scipy.org/
          - text: Contribute
            link: /ja/contribute
          - text: Code of Conduct
            link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
      column3:
        links:
          - text: FAQ
            link: /ja/faq
          - text: Terms of Use
            link: /ja/terms
          - text: Privacy
            link: /ja/privacy
          - text: Press Kit
            link: /ja/press-kit
          - text: Social Media
            link: /ja/about/#social-media
