name: style

on: [push, pull_request]

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
